# Generated by Django 3.1.5 on 2021-02-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Entry_time',
            field=models.TimeField(),
        ),
    ]
