# Generated by Django 3.1.5 on 2024-01-10 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0002_auto_20240110_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parking.location'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='parking_slot_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parking.parkingslot'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
