# Generated by Django 3.1.5 on 2021-02-18 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_auto_20210218_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location',
        ),
    ]
