# Generated by Django 3.1.5 on 2021-02-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_auto_20210219_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_name',
        ),
    ]
