# Generated by Django 3.1.5 on 2021-02-24 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_auto_20210223_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='lot',
        ),
        migrations.AddField(
            model_name='block',
            name='block_photo',
            field=models.ImageField(default='media/defaultblock.jpeg', upload_to='blocks/'),
        ),
        migrations.AddField(
            model_name='block',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parking.location'),
        ),
        migrations.AddField(
            model_name='location',
            name='building',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='building_photo',
            field=models.ImageField(default='media/auca.jpeg', upload_to='building/'),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='slot_photo',
            field=models.ImageField(default='media/defaultslot.jpeg', upload_to='slots/'),
        ),
        migrations.DeleteModel(
            name='ParkingLot',
        ),
    ]
